In [ ]:
# To-Do-Task

#basic vector and matrix operation with Numpy

#problem 1
#1) initialize an empty array with size 2x2

import numpy as np
array1=np.array((2,2))
print("#1",array1)

#2) initialize an array all ones 4x2
array2=np.array([[1,1],[1,1],[1,1],[1,1]])
print("#2",array2)

#3)return a new array with same shape and type as given array
newarr=np.full((2,2),2,dtype=int)
print("#3",newarr)

#4)return a new array of zeroes with the same type as given array
arr4=np.zeros((3,3),dtype=newarr.dtype)
print("#4",arr4)

#5) return a new array of ones with same shape and type as a given array
arr5=np.ones((3,3),dtype=newarr.dtype)
print("#5",arr5)

#6) for an existing list new_list=[1,2,3,4] convert to an nnumpy array
new_list=[1,2,3,4]
arr6=np.array(new_list)
print("#6",arr6)



#1 [2 2]
#2 [[1 1]
 [1 1]
 [1 1]
 [1 1]]
#3 [[2 2]
 [2 2]]
#4 [[0 0 0]
 [0 0 0]
 [0 0 0]]
#5 [[1 1 1]
 [1 1 1]
 [1 1 1]]
#6 [1 2 3 4]


In [ ]:
#problem2
import numpy as np
#1) create an array with values ranging from 10 to 49

array1=np.arange(10,50)
print("#1",array1)

#2) Create a 3x3 matrix with values ranging drom 0 to 8

array2=np.arange(0,9).reshape(3,3)
print("#2",array2)

#3) Create a 3x3 identity matrix

array3=np.eye(3)
print("#3",array3)

#4)create a random array of size30 and find the mean of the array
array4=np.random.random(30) # this creates an array of random number between 0 and 1
meanval=np.mean(array4)
print("#4 the mean value of array is:",meanval)

#5)create a 10x10 array with random values and find the minimum and maximum values
array5=np.array(np.random.random(100)).reshape(10,10)

print("the minimum value is:",np.min(array5))
print("the maximum value is:",np.max(array5))

#6)create a zero array of size 10 and replace 5th element with 1
array6=np.zeros(10)
array6[4]=1
print("#6",array6)


#7)Reverse an array arr= [1,2,0,0,4,0]
arr=np.array([1,2,0,0,4,0])
reversed=arr[::-1] # reverse the array (start to the end taking -1 steps)
print("#7 the reversed array is",reversed)

#8) create a 2d array with 1 on border and 0 inside
array8=np.ones((5,5))
array8[1:-1,1:-1]=0
print("#8",array8)


#9) create a 8x8 matrix and fill it with a checkboard pattern
array9=np.zeros((8,8),dtype=int)
array9[1::2,::2]=1
array9[::2,1::2]=1
print("#9",array9)








#1 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
#2 [[0 1 2]
 [3 4 5]
 [6 7 8]]
#3 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
#4 the mean value of array is: 0.45547800718048465
the minimum value is: 0.039500168747275466
the maximum value is: 0.9936428473334545
#6 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
#7 the reversed array is [0 4 0 0 2 1]
#8 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
#9 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [19]:
import numpy as np
#problem 3

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

#1) add two array
print("addition:",np.add(x,y))

#2)subtract two array
print("subtract:",np.subtract(w,v))

#3)multiply the array with any integer
mulx=x*4
muly=y*5
mulv=v*4
mulw=w*5
print("x multiplied by integer:",mulx)
print("y multiplied by integer:",muly)
print("v multiplied by integer:",mulv)
print("w multiplied by integer:",mulw)


#4)find the square of each element of the array
squaredx=x**2
squaredy=y**2
squaredv=v**2
squaredw=w**2
print("the squared array of x is:",squaredx)
print("the squared array of y is:",squaredy)
print("the squared array of v is:",squaredv)
print("the squared array of w is:",squaredw)

#5)find the dot product
dotx=np.dot(v,w)
dotx=np.dot(x,v)
dotx=np.dot(x,y)


print("the dot product btn v and w is:",dotx)
print("the dot product btn x and v is:",dotx)
print("the dot product btn x and y is:",dotx)

#6)Concatenate x(and)y along row and Concatenate v(and)w along column.
concatxny=np.concatenate((x,y),axis=0)
print("x and y concatenated along rows",concatxny)
concatvnw=np.column_stack((v, w))
print("v and w concatenated along columns",concatvnw)\

#7) concatenating x and v
#concatxnv=np.concatenate((x,v))
# the error observed wasn value error as the dimensions of the array didnt match each other
#print(concatxnv)



addition: [[ 6  8]
 [10 13]]
subtract: [2 2]
x multiplied by integer: [[ 4  8]
 [12 20]]
y multiplied by integer: [[25 30]
 [35 40]]
v multiplied by integer: [36 40]
w multiplied by integer: [55 60]
the squared array of x is: [[ 1  4]
 [ 9 25]]
the squared array of y is: [[25 36]
 [49 64]]
the squared array of v is: [ 81 100]
the squared array of w is: [121 144]
the dot product btn v and w is: [[19 22]
 [50 58]]
the dot product btn x and v is: [[19 22]
 [50 58]]
the dot product btn x and y is: [[19 22]
 [50 58]]
x and y concatenated along rows [[1 2]
 [3 5]
 [5 6]
 [7 8]]
v and w concatenated along columns [[ 9 11]
 [10 12]]


In [33]:
#problem 4

import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

#1)Prove A.A−1 = I.
# finding the inverse of A
invA=np.linalg.inv(A)
eqmultiplied=np.dot(A,invA)
print(" 1)hence proved \n A*A^-1=",eqmultiplied)

#2)Prove AB ̸= BA.
AxB=np.matmul(A,B)
BxA=np.matmul(B,A)
if np.array_equal(AxB,BxA):
    print("2) AB ̸= BA not proved")
else:
  print("2) AB ̸= BA equation proved")

#3)  prove (AB)^T=B^T A^T
ABtranspose=AxB.T
Bt_At=np.matmul(B.T, A.T)

if np.array_equal(ABtranspose, Bt_At):
  print("3)the equation (AB)^T=B^T A^T is proved")
else:
  print("3)the equation (AB)^T=B^T A^T is not proved")





 1)hence proved 
 A*A^-1= [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
2) AB ̸= BA equation proved
3)the equation (AB)^T=B^T A^T is proved


In [34]:
#problem 4) ii
import numpy as np
A= np.array([[2,-3,1],[1,-1,2],[3,1,-1]]) # x y and z elemets of left hand side

B=np.array([-1,-3,9]) #elements of right hand side

invA=np.linalg.inv(A)

X=np.dot(invA,B)
print('The value of x is:',X[0])
print('The value of y is:',X[1])
print('The value of z is:',X[2])



The value of x is: 2.0
The value of y is: 1.0
The value of z is: -2.0


In [35]:
#problem 4.2
import time
import numpy as np

list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000, 2000000)]
start = time.time()
result = [list1[i] + list2[i] for i in range(len(list1))]
end = time.time()
normal_time = end - start
print(f"Time taken for element-wise addition using Python lists: {normal_time:.5f} seconds")

#using numpy
array1 = np.arange(1000000)
array2 = np.arange(1000000, 2000000)
start2 = time.time()
result_array = array1 + array2
end2 = time.time()
numpy_time = end2 - start2
print(f"Time taken for element-wise addition using NumPy arrays: {numpy_time:.5f} seconds")

Time taken for element-wise addition using Python lists: 0.14918 seconds
Time taken for element-wise addition using NumPy arrays: 0.00431 seconds


In [36]:
#4.2) for elemetwise multiplication

import time
import numpy as np

list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000, 2000000)]
start = time.time()
result = [list1[i] * list2[i] for i in range(len(list1))]
end = time.time()
normal_time = end - start
print(f"Time taken for element-wise multiplication using Python lists: {normal_time:.5f} seconds")

array1 = np.arange(1000000)
array2 = np.arange(1000000, 2000000)
start2 = time.time()
result_array = array1 * array2
end2 = time.time()
numpy_time = end2 - start2
print(f"Time taken for element-wise multiplication using NumPy arrays: {numpy_time:.5f} seconds")


Time taken for element-wise multiplication using Python lists: 0.18852 seconds
Time taken for element-wise multiplication using NumPy arrays: 0.00463 seconds


In [37]:
#4.2) for dot product

import time
import numpy as np

list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000, 2000000)]
start = time.time()
dot_product = sum(list1[i] * list2[i] for i in range(len(list1)))
end = time.time()
normal_time = end - start
print(f"Time taken for dot product using Python lists: {normal_time:.5f} seconds")

array1 = np.arange(1000000)
array2 = np.arange(1000000, 2000000)
start2 = time.time()
dot_product_array = np.dot(array1, array2)
end2 = time.time()
numpy_time = end2 - start2
print(f"Time taken for dot product using NumPy arrays: {numpy_time:.5f} seconds")


Time taken for dot product using Python lists: 0.30714 seconds
Time taken for dot product using NumPy arrays: 0.00194 seconds


In [40]:
#4.2) for multiplication

import time
import numpy as np

n = 1000

matrix1 = [[i for i in range(n)] for j in range(n)]
matrix2 = [[i + 1 for i in range(n)] for j in range(n)]

start = time.time()
result_matrix = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(n)) for j in range(n)] for i in range(n)]
end = time.time()
normal_time = end - start
print(f"Time taken for matrix multiplication using Python lists: {normal_time:.5f} seconds")

array1 = np.random.rand(n, n)
array2 = np.random.rand(n, n)

start2 = time.time()
result_array = np.dot(array1, array2)
end2 = time.time()
numpy_time = end2 - start2
print(f"Time taken for matrix multiplication using NumPy arrays: {numpy_time:.5f} seconds")


Time taken for matrix multiplication using Python lists: 243.62491 seconds
Time taken for matrix multiplication using NumPy arrays: 0.06078 seconds


In [41]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful